### ISSUE TITLE
Country must be a fully formed ISO 3166-2 code if state parameter is omitted.

### ISSUE THREAD

**Issue by roman204** [wirecard/magento2-ee#437] opened 2020-05-31 14:00 UTC
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:**   2.3.3
**PHP version:** 7.2 

### Issue
Error when loading Creditcard Seamless Form and parameter regionCode is "null" (so isset but contains null) the following Exception is thrown: "Country must be a fully formed ISO 3166-2 code if state parameter is omitted."

`{"0":"Country must be a fully formed ISO 3166-2 code if state parameter is omitted.","1":"<pre>#1 Wirecard\\PaymentSdk\\Entity\\Address->setState() called at [vendor\/wirecard\/magento2-ee\/Gateway\/Helper\/AccountHolderMapper.php:89]\n#2 Wirecard\\ElasticEngine\\Gateway\\Helper\\AccountHolderMapper->updateAccountHolderAddress() called at [vendor\/wirecard\/magento2-ee\/Gateway\/Helper\/AccountHolderMapper.php:56]\n#3 Wirecard\\ElasticEngine\\Gateway\\Helper\\AccountHolderMapper->updateAccountHolder() called at [vendor\/wirecard\/magento2-ee\/Controller\/Frontend\/Creditcard.php:346]\n#4 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard->updateAccountHolder() called at [vendor\/wirecard\/magento2-ee\/Controller\/Frontend\/Creditcard.php:191]\n#5 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#6 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#7 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#8 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#9 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard\\Interceptor->___callPlugins() called at [generated\/code\/Wirecard\/ElasticEngine\/Controller\/Frontend\/Creditcard\/Interceptor.php:26]\n#10 Wirecard\\ElasticEngine\\Controller\\Frontend\\Creditcard\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#11 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#12 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#13 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#15 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#16 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:73]\n#17 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#21 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#22 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/wirecard_elasticengine\/frontend\/creditcard","script_name":"\/index.php"}`

**Problem description:**
The problem is that in magento configuration it is possible to make the "state" field not required but optional. And so the user gets an address object where "region" and "regionCode" is null but the key exists. 
The check for data with property_exists is not wrong but should be better than than that. 
https://github.com/wirecard/magento2-ee/blob/33b0db82e22cf39cba8f211b62523e30ec85ae49/Gateway/Helper/AccountHolderMapper.php#L88

**Steps to reproduce:**
* Put a product into the cart
* goto Checkout
* enter or select a address without selecting a region
* the controller "wirecard_elasticengine/frontend/creditcard" returns error 500 cause of the thrown exception and no form for entering data is shown.
...

**Comment by tomazpu** [comment] 2020-06-02 05:46
Hi @roman204, 

the issue is fixed and in are current RC candidate, I can link you the closed PR [here](https://github.com/wirecard/magento2-ee/pull/434).

It will be released in the next days, thank you for your very detailed report.
Best Regards, 
Tomaz

**Closed** 2020-06-02 08:52 UTC
Labels: issue

**Comment by tomazpu** [comment] 2020-06-02 08:59
Hi @roman204, 

there is a new release out wich should fix the issue.

Best regards,
Tomaz
