### ISSUE TITLE
Credit card payment currency issue

### ISSUE THREAD

**Issue by thomas-WD** [wirecard/magento2-ee#161] opened 2018-11-12 03:35 UTC
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions
**Magento version:** 2.2.6
**PHP version:**  7.0.32

### Issue
Account must enabled with EUR, otherwise the checkout seamless form can't be loaded
**Problem description:**
Tried credit card payment with an account doesn't accept currency EUR but HKD as the default currency in the Magento configuration, and find the seamless checkout form returned "Not ready.. " from posting to /engine/rest/seamless/renderform . When the program code changed in **TransactionService.php**, from 'EUR' to 'HKD', it works. 
requested_amount_currency' => is_null($amount) ? 'EUR' : $amount->getCurrency(),
changed to:
requested_amount_currency' => is_null($amount) ? 'HKD' : $amount->getCurrency(),

--

...

**Steps to reproduce:**
1. Use a EE account and do the set-up does not allow currency EUR and allow another currency such as HKD
2. In the Magento configuration, choose the default currency to HKD
3. Try to checkout a item with credit card
4. It shows "an error loading the credit card form".

...

**Comment by tomazpu** [comment] 2018-11-12 06:38
Hello, 

can you please provide us with the plugin version, and the paymentSDK version you are using?

Best regards, thank you. 
Tomaz

**Comment by thomas-WD** [comment] 2018-11-12 09:14
wirecard/iso-paypal-converter                     1.0.0     
wirecard/magento2-ee                              1.3.10    
wirecard/payment-sdk-php                          3.4.2

**Comment by tomazpu** [comment] 2018-11-12 09:58
thank you, i will take a detailed look at it and come back to you when i know more.

**Comment by tomazpu** [comment] 2018-11-12 13:17
The issue is fixed with the new release(1.3.11) -> https://github.com/wirecard/magento2-ee/releases/tag/1.3.11

I will close the issue, thank you for your report.
Best regards Tomaz

**Closed by tomazpu** 2018-11-12 13:17 UTC
